on:
  pull_request:
    types:
      - closed

jobs:
  stable_website_cherry_pick:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'docs-cherrypick')
    runs-on: ubuntu-latest
    name: Cherry pick to stable-website branch
    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      with:
        ref: stable-website
    - run: |
        git fetch --no-tags --prune origin main
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git cherry-pick ${{ github.sha }}
        git push origin stable-website
